spring.application.name=budget-service
server.port=8081
spring.data.mongodb.uri=mongodb+srv://geetyouknow_db_user:gwJ4okEcZ1Y0lRbC@eventcluster.ki34sea.mongodb.net/budget_service_db?retryWrites=true&w=majority
logging.level.org.springframework.data.mongodb=DEBUG